### ISSUE TITLE
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 131072 bytes

### ISSUE THREAD

**Issue by TemporalAgent7** [zhangjiequan/AssetStudio#26]
I get this error on every file I want to open from the game Whiteout Survival. Any tips?

I saw https://github.com/zhangjiequan/AssetStudio/issues/15 but in my case there is a single instance of the "UnityFS" string in the file (first characters).

```
Error while reading bundle file D:\work\whiteout\apk\assets\data\actor_battle_battle_gpu_soldier_archer_blue_906b8dd885c6cb6653e843cd67dc4a6.unity3d
System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 131072 bytes
   at AssetStudio.BundleFile.ReadBlocks(EndianBinaryReader reader, Stream blocksStream) in D:\work\whiteout\AssetStudio\AssetStudio\BundleFile.cs:line 353
   at AssetStudio.BundleFile..ctor(FileReader reader) in D:\work\whiteout\AssetStudio\AssetStudio\BundleFile.cs:line 98
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath) in D:\work\whiteout\AssetStudio\AssetStudio\AssetsManager.cs:line 182
```

The files appear to have version `5.x.x 2018.4.36f1`

**Comment by bahraini69** [comment]
Hey have you found anything new about this ?

**Comment by AxiomCount** [comment]
I think this fork of the AssetViewer just doesn't support games compiled on new Unity
